<?php

namespace JobMetric\Url\Events;

/**
 * Class UrlableResourceEvent
 *
 * Event carrying a urlable model so listeners can produce and attach a
 * resource representation to it. Listeners are expected to read the
 * {@see $urlable} property and write the resulting resource into
 * {@see $resource}.
 */
class UrlableResourceEvent
{
    /**
     * Holds the urlable model instance associated with the URL.
     *
     * @var mixed
     */
    public mixed $urlable;

    /**
     * Holds the resource generated by listeners for the given urlable.
     * Left null by default and should be set by event listeners.
     *
     * @var mixed
     */
    public mixed $resource = null;

    /**
     * Create a new event instance.
     *
     * @param mixed $urlable The related model instance for which a resource should be resolved.
     */
    public function __construct(mixed $urlable)
    {
        $this->urlable = $urlable;
    }
}
